services:
  huginn:
    image: ghcr.io/huginn/huginn:latest # GHCR imaj adı
    environment:
      - DATABASE_ADAPTER=mysql2
      - DATABASE_HOST=db
      - DATABASE_NAME=huginn
      - DATABASE_USERNAME=huginn
      - DATABASE_PASSWORD=huginn
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0 # Resmi MySQL imajı
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=huginn
      - MYSQL_USER=huginn
      - MYSQL_PASSWORD=huginn
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
